version: '3'

services:
  toj-redis:
    image: redis
    command: redis-server --port 6379
    ports:
      - "6379:6379"

  toj-app:
    container_name: toj_app
    image: leekujin14/toj-app
    ports:
      - 8080:8080
    depends_on:
      - toj-redis
    env_file:
      - .env